name: golangci (multi OS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]
  
jobs:
    golangci:
      strategy:
        matrix:
          go-version: [ stable ]
          os: [ubuntu-latest, macos-latest, windows-latest]
      uses: ./.github/workflows/.golangci-reusable.yml
      secrets: inherit
      with:
        os: ${{ matrix.os }}
        go-version: ${{ matrix.go-version }}
        golangci-lint-version: v1.62.0
        sonar-scanner-version: 6.2.1.4610
        projectBaseDir: .
        args: >
          --out-format=colored-line-number
